spring:
  application:
    name: product-service

  jackson:
    datatype:
      datetime:
        write-dates-as-timestamps: false

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/productdb}
    username: ${DB_USERNAME:productuser}
    password: ${DB_PASSWORD:productpass}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info